<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
	<TargetFramework>net48</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<LangVersion>latest</LangVersion>
</PropertyGroup>

<ItemGroup>
  <PackageReference Include="System.Memory" Version="4.6.3" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BinarySharp\BinarySharp.csproj" />
  </ItemGroup>

</Project>
